#Docker-compose.qa.yml
version: '3.7'

services:
  fatboar-back:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=qa"
      - "traefik.frontend.rule=Host:preprod-backend.fatboar.tk"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
