version: '3.7'

services:
  fatboar-back:
    image: fatboar-back:latest
    container_name: fatboar-back
    depends_on:
      - fatboar-back-database
    environment:
      - spring_datasource_url=jdbc:mysql://fatboar-back-database/fatboardb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      - spring_datasource_username=springuser
      - spring_datasource_password=springuser
      - FATBOAR_CALLBACK_BASE_URL=https://dev.fatboar.tk
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dev"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:dev-backend.fatboar.tk"
    networks:
      - web
    volumes:
      - backend-logs:fatboar-back/logs
  fatboar-back-database:
    image: mysql:8.0.14
    container_name: fatboar-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fatboardb
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=springuser
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - web
volumes:
  dbdata:
  backend-logs:
    external:
      name: workflow_prod-backend-logs
networks:
  web:
    external: true
