version: '3.7'

services:
  fatboar-back-exec:
    image: fatboar-back:latest
    container_name: fatboar-back
    depends_on:
      - fatboar-back-database
    environment:
      - spring_datasource_url=jdbc:mysql://fatboar-back-database/springboot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      - spring_datasource_username=springuser
      - spring_datasource_password=springuser
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dev"
      - "traefik.frontend.rule=Host:dev.fatboar.tk"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
    networks:
      - web
  fatboar-back-database:
    image: mysql:8.0.14
    container_name: fatboar-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fatboardb
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=springuser
    volumes:
      - dbdata:/var/lib/mysql
      - backend-logs:/logs
    networks:
      - web
volumes:
  dbdata:
  backend-logs:
networks:
  web:
    external: true
