version: '3.7'

services:
  fatboar-back:
    image: fatboar-back:latest
    container_name: fatboar-back
    depends_on:
      - mysql
    environment:
      - spring_datasource_url=jdbc:mysql://mysql:3306/fatboardb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      - spring_datasource_username=springuser
      - spring_datasource_password=springuser
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dev"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:dev-backend.fatboar.tk"
    networks:
      - web

networks:
  web:
    external: true
